const CREATED = 201;
const OK = 200;
const BAD_REQUEST = 400;
const ACCESS_ERROR = 401;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
module.exports(CREATED, OK, BAD_REQUEST, ACCESS_ERROR, NOT_FOUND, SERVER_ERROR);
